# Generated by Django 2.0.5 on 2018-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('display_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
